version: '3'

services:
    mysql:
        image: mysql
        container_name: coffee-machine.mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'coffee_machine'
            MYSQL_DATABASE: 'coffee_machine'
            MYSQL_USER: 'coffee_machine'
            MYSQL_PASSWORD: 'coffee_machine'
        ports:
            - "3305:3306"

