version: '3'

services:
    mysql:
        image: mysql
        container_name: coffee-machine.mysql
        volumes:
          - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'coffee_machine'
            MYSQL_DATABASE: 'coffee_machine'
            MYSQL_USER: 'coffee_machine'
            MYSQL_PASSWORD: 'coffee_machine'
            MYSQL_ROOT_HOST: '%'
        expose:
            - '3306'
        ports:
            - "3305:3306"
        networks:
            - coffee_machine_net
networks:
    coffee_machine_net:
        external: true
volumes:
    db_data: {}

            